[package]
name = "docker-transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
docker-api = { version = "0.12.2", chrono = true, tls = true }
tokio = { version = "1", features = ["full"] }